apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: iagentic
  name: iagentic-pvc
  namespace: iagentic
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi